spring:
  application:
    name: auth-server
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: production
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/


keycloak:
  realm: mockapi
  domain: localhost:8081
  adminClientId: admin-cli
  adminClientSecret: LjWXNqPjgwR0HEcJXfmVHov0x4uGipc5
  client: springboot-rest
  urls:
    auth: http://${keycloak.domain}


jwt:
  auth:
    converter:
      resource-id: springboot-rest

server:
  port: 8010