spring:
  application:
    name: resource-server
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3307/mockapi
    username: root
    password: password
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}

keycloak:
  realm: mockapi
  domain: localhost:8081

openapi:
  service:
    title: resource-service doc
    version: 1.0.0
    url: http://localhost:8080 #api gateway url
springdoc:
  api-docs:
    path: /resource-server/v3/api-docs
  swagger-ui:
    path: /resource-server/swagger-ui.html

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

server:
  port: 8020

jwt:
  auth:
    converter:
      resource-id: springboot-rest
